# Generated by Django 5.2.7 on 2025-10-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_name_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
