# Generated by Django 5.2.7 on 2025-10-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_category_image_alter_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
